### ISSUE TITLE
[BUG] Quote does not display again.

### ISSUE THREAD

**Issue by SimonZindo** [twentytwokhz/quote-of-the-day#13]
Thank you so much for creating this plugin, as it randomly generates a new quote. But lately, I have been facing a little issue with it.

Anytime I want to insert a new quote it is " > Oops, I did it again 🙊
> &mdash; <cite>Britney Error 😢</cite>✍️"

I tried to uninstall and reinstall. To ensure my obsidian vault was not an issue, I created a new obsidian vault, but it said the same thing.
It could be a bug.

I will be delighted to hear back from you.

**Comment by twentytwokhz** [comment]
Should work now in version 1.0.3
