### ISSUE TITLE
[BUG] https://api.quotable.io/ no longer working

### ISSUE THREAD

**Issue by bprager** [twentytwokhz/quote-of-the-day#18]
**Describe the bug**
The plugin is no longer working is the source https://[api.quotable.io](https://api.quotable.io/)/ is no longer available.

**Comment by kiuwan1007** [comment]
help same problem here too!!!

**Comment by rickymolnar** [comment]
Here to report the same issue!

**Comment by DerekBT** [comment]
Same here.

**Comment by twentytwokhz** [comment]
Yes, checked and it seems to be an issue on their end. I managed to find a solution. Will update ASAP

**Comment by twentytwokhz** [comment]
Thought the solution would be easier. It seems the quotable API is down.
I'm working on creating a new api that would perform the same tasks.

WIP

**Comment by twentytwokhz** [comment]
Issue resolved, replaced by my own enhanced api
