### ISSUE TITLE
[FEATURE] Add a backup to Luke Peavey's Quotable API

### ISSUE THREAD

**Issue by MarkOSullivan94** [twentytwokhz/quote-of-the-day#19]
**Is your feature request related to a problem? Please describe.**

The [quotable API by Luke Peavey](https://github.com/lukePeavey/quotable/issues) has been down since 11th September for me and as a result I haven't seen any quote of the day since then.

**Describe the solution you'd like**

By having an alternative API then we wont have any issues should the API hosted by Luke Peavey goes down

An alternative API has been provided here: https://github.com/lukePeavey/quotable/issues/239#issuecomment-2344094395

In addition to having a backup API having the ability to enter URLs for alternative APIs would be useful

**Comment by twentytwokhz** [comment]
No worries, I already created a new API for quotes that has a larger dataset, almost 500k quotes
Fixed in version 1.0.3
