### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gsanchez2004** [twentytwokhz/quote-of-the-day#20]
** QOTD is not working **

"Oops, I did it again" qotd is appearing each time i try to use the plugin

i´ve checked the plugin code and apparently the reffering app "https://florinbobis-quotes-net.hf.space/quotes" is not working 

please can it be repaired ?

Thanks in advance !

**Comment by twentytwokhz** [comment]
Api being used was on a server that was offline. Now it's back online
