### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ananas0631** [twentytwokhz/quote-of-the-day#21]
**Describe the bug**

**To Reproduce**
1. Using hotkey 'ctrl + alt + q' to insert random quote of the day
2. See error

**Expected behavior**
Just to see some random quotes

**Screenshots**
![image](https://github.com/user-attachments/assets/82b4987f-e614-4574-b5bd-1c702500ae75)
![image](https://github.com/user-attachments/assets/3d641c16-7c46-45db-b632-0de94870a2cc)

**Comment by twentytwokhz** [comment]
Api being used was on a server that was offline. Now it's back online
