### ISSUE TITLE
Feature request: placeholder for templates

### ISSUE THREAD

**Issue by swehba** [twentytwokhz/quote-of-the-day#3]
Nice plugin. Thanks. Would be nice to support a placeholder that is automatically evaluated to insert a quote when a template is applied. I think the most common use case for your plugin will be to add a quote to the daily note, and having a template placeholder would be a nice feature. Thanks again.

**Comment by mashingkeys** [comment]
I'm seconding this request. I'd love to use this to insert a random quote of the day in my daily note template, but at the moment it would just carry over the same quote .

Thanks!

**Comment by T-Damer** [comment]
Need this feature, good to have life advice when you open your daily note :)

**Comment by twentytwokhz** [comment]
This feature is now implemented.
Also added random quotes based on Quotable API tags.

Let me know what you think 😉

**Comment by joyskmathew** [comment]
if the random quotes that are implemented currently get updated automatically without inserting another quote, it would be really nice
