### ISSUE TITLE
{{qotd}} merge tag not working

### ISSUE THREAD

**Issue by ShaheedFazal** [twentytwokhz/quote-of-the-day#7]
Hi,

Just installed your plugin and although I have put {{qotd}} as part of a template, it does not seem to display a quote on my daily notw.

Do I need to configure further?

Thnanks

Shaheed

**Comment by naheller** [comment]
Hi Shaheed - did you enable the plugin after installing it?

**Comment by ShaheedFazal** [comment]
It seems to be working now. I have been having issues with iCloud not syncing across devices and I think that may have been the issue. Sorry to have troubled you.
